apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: pipelines-vote-ui
  name: pipelines-vote-ui
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: pipelines-vote-ui
    weight: 100
